import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/Navbar";

import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import CircleAnimation from "./components/Cursor";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Persista",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {children}
//       </body>
//     </html>
//   );
// }
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CircleAnimation />
        <div className="page-container">
          <Navbar />
          <main className="content-wrapper">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
